
export const PLATFORMS = {
  x: {
    id: "x",
    name: "X",
    stamp: "𝕏",
    color: "#14213d",
    charLimit: 280,
    maxHashtags: 5,
    supportsThreads: true,
    supportsMedia: true,
    maxMedia: 4,
    mediaLabel: "images/GIF/video",
    voice: "clipped, punchy, one idea per line, low ceremony",
    bestHoursLocal: [8, 9, 12, 17, 18],
  },
  threads: {
    id: "threads",
    name: "Threads",
    stamp: "@",
    color: "#14213d",
    charLimit: 500,
    maxHashtags: 3,
    supportsThreads: true,
    supportsMedia: true,
    maxMedia: 10,
    mediaLabel: "images/video",
    voice: "conversational, a little wry, reads like a text to a friend",
    bestHoursLocal: [9, 13, 19, 21],
  },
  linkedin: {
    id: "linkedin",
    name: "LinkedIn",
    stamp: "in",
    color: "#0a66c2",
    charLimit: 3000,
    maxHashtags: 5,
    supportsThreads: false,
    supportsMedia: true,
    maxMedia: 9,
    mediaLabel: "images/document/video",
    voice: "narrative, structured with a hook + lesson, professional but human",
    bestHoursLocal: [7, 8, 12, 17],
  },
  instagram: {
    id: "instagram",
    name: "Instagram",
    stamp: "◎",
    color: "#c1327a",
    charLimit: 2200,
    maxHashtags: 30,
    supportsThreads: true, // carousel
    supportsMedia: true,
    maxMedia: 10,
    mediaLabel: "images/video (media required)",
    mediaRequired: true,
    voice: "visual-first caption, warm, hashtags clustered at the end",
    bestHoursLocal: [11, 13, 19, 20],
  },
  facebook: {
    id: "facebook",
    name: "Facebook",
    stamp: "f",
    color: "#1877f2",
    charLimit: 63206,
    maxHashtags: 3,
    supportsThreads: false,
    supportsMedia: true,
    maxMedia: 10,
    mediaLabel: "images/video/link",
    voice: "friendly, a bit longer-form, minimal hashtags",
    bestHoursLocal: [9, 13, 15],
  },
  medium: {
    id: "medium",
    name: "Medium",
    stamp: "M",
    color: "#1a1a1a",
    charLimit: 100000,
    maxHashtags: 5,
    supportsThreads: false,
    supportsMedia: true,
    maxMedia: 30,
    mediaLabel: "images (cover image recommended)",
    voice: "long-form essay, a strong hook paragraph, clear subheadings, a considered close",
    bestHoursLocal: [7, 8, 20],
    requiresTitle: true,
    longForm: true,
  },
  substack: {
    id: "substack",
    name: "Substack",
    stamp: "S",
    color: "#ff6719",
    charLimit: 100000,
    maxHashtags: 5,
    supportsThreads: false,
    supportsMedia: true,
    maxMedia: 30,
    mediaLabel: "images",
    voice: "personal newsletter voice — direct address to the reader, a clear throughline",
    bestHoursLocal: [7, 9],
    requiresTitle: true,
    longForm: true,
  },
};

export const PLATFORM_LIST = Object.values(PLATFORMS);

export const getPlatform = (id) => PLATFORMS[id];
